### ISSUE TITLE
Border Width is duplicated on image

### ISSUE THREAD

**Issue by DerMth** [kfiroo/react-native-cached-image#100]
Hi,

There is an issue when setting a `borderWidth` style on an image.
When I set a borderWidth, the border is "duplicated" on iOS (not tested on Android).
![capture d ecran 2017-10-20 a 11 15 31](https://user-images.githubusercontent.com/5585647/31813976-7a3e12c2-b588-11e7-8a03-18b30e4ebcc2.png)

Here is my image style : 
```
const RoundedImage = styled(CachedImage)`
    width: 100px;
    height: 100px;
    borderColor: green;
    borderWidth: 3px;
`;
```

The radius in the screenshot or the Styled Component in the code are not important, the result is the same without. 

I used the initial React Native image before and had no issue.

**Comment by kfiroo** [comment]
@DerMth Hey,
If you take a look at the code [here](https://github.com/kfiroo/react-native-cached-image/blob/d9a6a943d5093d45c57b60541d6c9da4d626bea1/CachedImage.js#L55) you can see we are rendering a `BackgroundImage` component with the styles provided to `CachedImage`.

Can you try rendering the `BackgroundImage` component and see if the problem still exists?

**Comment by DerMth** [comment]
@kfiroo Hi,
The border seems not "duplicated" with the `ImageBackground`, but the image is not anymore rounded.
<img width="89" alt="capture d ecran 2017-10-23 a 13 52 12" src="https://user-images.githubusercontent.com/5585647/31887685-93b1eec2-b7f9-11e7-828f-b0d95d8b0f6a.png">

**Comment by kfiroo** [comment]
@DerMth note that `ImageBackground` uses `imageStyle` prop for styles

**Comment by bdavid68** [comment]
@DerMth Since this library renders the *ImageBackground* with the styles provided to *CachedImage*, you can try this.

```
  avatarWrapper: {
    height: 100,
    width: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatar: {
    height: 100,
    width: 100,
  },
....
<View style={styles.avatarWrapper}>
   <CachedImage
      style={styles.avatar}
      source={avatarSource}
   />
</View>
```

**Comment by DerMth** [comment]
@kfiroo @bdavid68 Thanks for your answers. 
I first used the method of @bdavid68, but in order to have less code, I used the `imageStyle` property : ` imageStyle={{ borderRadius: xx }}`
