### ISSUE TITLE
Move unmaintained react-native-fetch-blob dep to rn-fetch-blob

### ISSUE THREAD

**Issue by fungilation** [kfiroo/react-native-cached-image#122]
From https://github.com/wkh237/react-native-fetch-blob/blob/master/README.md:

> wkh237's last Github activity was in September 2017, and he has not reacted to emails either. This repository no longer is the main location of "react-native-fetch-blob".
> 
> The owners of this fork have agreed to maintain this package:
> 
> **https://github.com/joltup/rn-fetch-blob/releases**
> 
> That means issues and PRs should be posted there.

`rn-fetch-blob` includes pending PR like https://github.com/wkh237/react-native-fetch-blob/pull/674, to fix bugs I'm seeing like https://github.com/facebook/react-native/issues/19960#issuecomment-401432570

Migrating simply involves removing dependency on `react-native-fetch-blob`, and adding `rn-fetch-blob`.

**Comment by jose920405** [comment]
Related to this issue https://github.com/kfiroo/react-native-cached-image/issues/121

**Comment by fungilation** [comment]
Fixed in my [fork](https://github.com/fungilation/react-native-cached-image/commits/master) and PR (unlikely to be merged given this repo seems to be unmaintained)

**Comment by ShaMan123** [comment]
lucky I found this
