### ISSUE TITLE
How to get local image path?

### ISSUE THREAD

**Issue by LeoTianJLL** [kfiroo/react-native-cached-image#13]
I tried to use `ImageCacheProvider.getCachedImagePath()` function to access downloaded local files with URL links, but I don't know how to use the returned `Promise<imagePath: string>`. The result is shown as follows:
<img width="1423" alt="screen shot 2017-03-23 at 12 34 59 pm" src="https://cloud.githubusercontent.com/assets/17267466/24232457/1d19b924-0fc6-11e7-841b-9cbd3186f777.png">
I outputted the `Promise<imagePath: string>`. 
The first line shows the value of key `_65` is null and it‘s indeed null when I try to get this value in my app.  But why can I see a local path after expanding the node and how can I use it?

**Comment by kfiroo** [comment]
Hey @LeoTianJLL 
Look here https://github.com/kfiroo/react-native-cached-image/blob/master/CachedImage.js#L119 for an example of how to get the local path.

```jsx
ImageCacheProvider.getCachedImagePath(url, options)
    .then(cachedImagePath => {
        // do something with cachedImagePath
    })
    .catch(err => {
        // local image for the given url does not exist
        // or there has been an error
    });
```

**Comment by LeoTianJLL** [comment]
Hi @kfiroo , this is quit helpful. Thanks for your help.
