### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by andrelimawork** [kfiroo/react-native-cached-image#14]
Hello,
I'm having some problems the first time i declare a CachedImage.
It looks that it's trying to find the image and the error is not being handled.
Do you experience the same problem?

YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0): The file “50c5db50fca5ad9306dce6d1e947ba1781e0ab41.jpg” couldn’t be opened because there is no such file. Error: The file “50c5db50fca5ad9306dce6d1e947ba1781e0ab41.jpg” couldn’t be opened because there is no such file.

Nice module,
Keep the good work

**Comment by andrelimawork** [comment]
Hey the problem is not in your module, sorry for that;)

**Comment by zeekay18** [comment]
hey @andrelimawork how did you resolve this issue
