### ISSUE TITLE
react-native-fs has been deprecated

### ISSUE THREAD

**Issue by Froelund** [kfiroo/react-native-cached-image#15]
Author of the library points to [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) as an alternative

**Comment by kfiroo** [comment]
@Froelund Thanks for the heads up! :)
I will look into replacing `RNFS` with `RNFB`, for now everything should continue working.

Looks like `RNFB` handles caching files internally, which means less code for us :)

**Comment by kfiroo** [comment]
Published v1.3.0 that uses `react-native-fetch-blob`
