### ISSUE TITLE
ActivityIndicator showing up even when images are already downloaded

### ISSUE THREAD

**Issue by rodperottoni** [kfiroo/react-native-cached-image#18]
I'm experiencing something weird when downloading images with the **ImageCacheProvider**. I have ~15 images being downloaded the first time I open my app. I can confirm they're being successfully saved but every time I have to load them I can see the following behaviour:

1 - I open a new window that has a CachedImage component on it.
2 - The CachedImage component doesn't show up at all (just like it has **height: 0** and **width: 0**
3 - After ~200ms the CachedImage component shows up as a blank square (height and width are now correctly set
3 - After ~200ms the **ActivityIndicator** shows up
4 - After ~200ms the image finally shows up.

Is that normal/expected? How can I prevent that transition between steps 2-3 (where I can see the image container growing) ? Thanks!

**Comment by kfiroo** [comment]
Hey @rodperottoni, not sure what's going on there.
This is not the expected behaviour, you should see the activity indicator immediately and the image as soon as it is available.

Maybe you could post some code?

**Comment by rodperottoni** [comment]
Please close this issue. I'm at a point where I can't properly debug this issue because of my project's timeline. Thanks for replying though.
