### ISSUE TITLE
how to use the useQueryParamsInCacheKey property

### ISSUE THREAD

**Issue by ajonno** [kfiroo/react-native-cached-image#21]
hi there, thanks for this library !

can you provide quick example of how ```useQueryParamsInCacheKey``` can be used ? 

also im not sure if this is/should be, a feature of this library but is it possible to apply (lets say) a "tag" to an image so that later, we can retrieve it via a query=`tag` ?

**Comment by kfiroo** [comment]
Hey @ajonno 
By default we don't use the query params when generating the cache key for the image url.
For example, the url `https://www.example.com/some/image?imageId=img1` and `https://www.example.com/some/image?imageId=img2` would be mapped to the same file in the file system, not what we wanted :)
Introducing `useQueryParamsInCacheKey` to the rescue, it can take `bool` value indicating whether to use **all** query keys when generating the cache key or not.
Sometimes you might only need to use part of the query string, like when you have `https://www.example.com/some/image?imageId=img3&ts=<Date.now()>`,  for these cases you can pass an array of the keys you want to use, in this case `['imageId']`

Hope that makes it clearer :)
