### ISSUE TITLE
support get total cache size

### ISSUE THREAD

**Issue by YouHan26** [kfiroo/react-native-cached-image#23]
if possible, can you help to support get cache size?

**Comment by kfiroo** [comment]
@YouHan26 Hey, this does not come out of the box with `react-native-fetch-blob` so I will have to figure out an other way to do it.
For now I'm thinking about traversing all files under the base cache dir and collecting their file sizes, however this seems a bit too wasteful to do over the RN bridge.

Any suggestions are welcome here :)

**Comment by YouHan26** [comment]
@kfiroo yeah, I have used traversing all files to get total size. It looks not so slow. I can accept it. Need I commit a pr?
Thanks a lot for your work of `cached-image` component, It help me a lot. :)

**Comment by kfiroo** [comment]
@YouHan26 I would prefer to have a single call to the native code to retrieve this info, I would look into `react-native-fetch-blob` fs code to see if it's possible.

Glad you find it helpful! :)

**Comment by kfiroo** [comment]
@YouHan26 Hey, master has a version with a working `getCacheInfo` that returns the following format
```jsx
{
  files: [// an array of all files in the cache represented by their `fs.stat()` result],
  size: 0 // size of cache in bytes (see example)
}
```
Hope that helps

**Comment by YouHan26** [comment]
@kfiroo it works. Thanks

**Comment by MossP** [comment]
@YouHan26 How did you then delete those images from the cache seeing as you don't have the pre-hash filenames?

**Comment by MossP** [comment]
Ah. I think I see it.. there are other function in the ImageCacheProvider that I can probably use. I'll try those directly.
