### ISSUE TITLE
Suggestion: passing a customised ActivityIndicator or SpinnerComponent

### ISSUE THREAD

**Issue by gameboyVito** [kfiroo/react-native-cached-image#25]
I have read your source code and found that there is no way to pass a customised loading spinner to replace the default ActivityIndicator. The default one is ugly and I would like to replace it with my own component. Maybe you can just rewrite `renderLoader() ` to support this feature. Or I can just send you a PR if you are acceptable.

**Comment by kfiroo** [comment]
@gameboyVito Great suggestion, PRs are welcome! :)

**Comment by kfiroo** [comment]
resolved here https://github.com/kfiroo/react-native-cached-image/releases/tag/v1.3.5
