### ISSUE TITLE
Unhandled JS Exception: undefined is not an object (evaluating 'RNFetchBlob.DocumentDir')

### ISSUE THREAD

**Issue by jose920405** [kfiroo/react-native-cached-image#39]
using:
`npm install react-native-cached-image --save`

and later

`react-native link react-native-fetch-blob`.

![simulator screen shot may 9 2017 11 17 37 am](https://cloud.githubusercontent.com/assets/12536184/25861024/1fc8920a-34a9-11e7-8e34-49626e6cf84e.png)

**react-native -v**
react-native-cli: 2.0.1
react-native: 0.33.0

"react": "~15.3.2",
"react-native": "0.33.0",

i'm follow [this](https://github.com/wkh237/react-native-fetch-blob/wiki/Trouble-Shooting#user-content-undefined-is-not-an-object-evaluating-rnfetchblobdocumentdir) for fix it, but notting works

**Comment by witalobenicio** [comment]
@jose920405 why did you close it? You found a solution?

**Comment by jose920405** [comment]
hi @witalobenicio yes i close this issue because the problem was not related with this module. To be honest i not remember the real cause, i just remember that there was something I was doing wrong

**Comment by dgritsko** [comment]
For anyone else who comes across this issue and is still looking for a solution, I had to run `pod install` after following the instructions on README.md before things worked for me on iOS.

**Comment by muhammadsr** [comment]
For iOS, make sure you do `pod install`
For Android, follow this https://github.com/wkh237/react-native-fetch-blob/issues/251#issuecomment-280760756

**Comment by abdullah253d2** [comment]
and for expo?
