### ISSUE TITLE
Cannot nest component inside TouchableOpacity

### ISSUE THREAD

**Issue by dstik** [kfiroo/react-native-cached-image#4]
Hey - great work on this component!

I found that currently, attempting to nest a `<CachedImage/>` as a child inside a `<TouchableOpacity/>` throws:

> Invariant Violation: Touchable child must either be native or forward setNativeProps to a native component.

This is blocking us and may block others so I have submitted a PR to resolve this issue: https://github.com/kfiroo/react-native-cached-image/pull/3

**Comment by kfiroo** [comment]
Fixed with v1.2.1
