### ISSUE TITLE
When I use the same two CachedImage urls, there will be problems

### ISSUE THREAD

**Issue by z372183629** [kfiroo/react-native-cached-image#43]
`render() {
    return (
      <View>
        <TouchableWithoutFeedback onPress={() => {
          this.setState({showModal: true})
        }}>
          <CachedImage
            source={{uri: 'http://p10.qhimg.com/t019e9cf51692f735be.jpg'}}
            resizeMode="contain"
            style={{width: 100, height: 100}}
          />
        </TouchableWithoutFeedback>
        <Modal
          visible={this.state.showModal}
          animationType='fade'
          onRequestClose={() => {
            this.setState({showModal: false})
          }}>
          <TouchableWithoutFeedback onPress={() => {
            this.setState({showModal: false})
          }}>
            <CachedImage
              source={{uri: 'http://p10.qhimg.com/t019e9cf51692f735be.jpg'}}
              resizeMode="contain"
              style={{flex: 1}}
            />
          </TouchableWithoutFeedback>
        </Modal>
      </View>
    )
  }`

If the first image is being downloaded and then I turn on the Modal, Modal will show an incomplete picture.This means that the download is closed and a wrong image is retained.

**Comment by z372183629** [comment]
I think there is a problem with the function **getCachedImagePath**, It should be, if the URL is being downloaded, return its Promise or return the file path

**Comment by kfiroo** [comment]
@z372183629 Good catch! I'll look into it.
If you want you can submit a pull request with a fix :)

**Comment by MossP** [comment]
Did you find a fix @z372183629 ?
