### ISSUE TITLE
Problem with file path on Android

### ISSUE THREAD

**Issue by aterribili** [kfiroo/react-native-cached-image#49]
The files paths are coming without prefix `file://` on Android, because that, the file address becomes incorrect, so I need to append `file://` to file path.

On iOS it's ok. 

I'm using `getCachedImagePath` method.

Thank you for the lib, it's very awesome!

If you need some help, please let me know.

**Comment by kfiroo** [comment]
@aterribili I'm using it on both iOS and Android and I don't seem to have this issue.
What am I missing?

**Comment by aterribili** [comment]
I'll investigate better :)

**Comment by kfiroo** [comment]
@aterribili Let me know if I can help in any way!
