### ISSUE TITLE
Export an AnimatedCachedImage

### ISSUE THREAD

**Issue by kytwb** [kfiroo/react-native-cached-image#62]
That would work the same but use an `Animated.Image` so images can be animated (e.g. fading for progressive images). That's something I would be keen to look at if I get the go for a PR from one of the maintainer.

**Comment by DavoCg** [comment]
+1

**Comment by kfiroo** [comment]
@kytwb By all means go for it! :)

**Comment by ChristianTucker** [comment]
It's funny, because I was just about to make this PR.

**Comment by kytwb** [comment]
Hi guys. Just wanted your feedback on couple of things. 

Any drawback if I just replace the `Image` by an `Animated.Image`? 

Also, with the current code base, it's not possible to passe the animated style value (e.g. `opacity`) through the usual `style` prop as  `this.props.style` is applied to other elements than just the `Animated.Image` element and result in an error like `cannot assign to read only property` if I recall properly.

You can see the quick hack I did [here](https://github.com/kytwb/react-native-cached-image/commit/02add0d5b3d814eb21b3c540ce0cfcb933d447f2).
Will eventually make a PR and get feedbacks from there if I see no replies here.

**Comment by kfiroo** [comment]
@kytwb Hey! 
What about simply using `renderImage` to render the `Animated.Image` with the props you want?

**Comment by kytwb** [comment]
@kfiroo right, I wasn't aware of the `renderImage`, good call!
