### ISSUE TITLE
NetInfo's "change" event is deprecated

### ISSUE THREAD

**Issue by kytwb** [kfiroo/react-native-cached-image#75]
After upgrading to latest React Native (0.48.0) I keep getting this warning:

`NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead.`

I guess this is due to: https://github.com/kfiroo/react-native-cached-image/blob/6aac3174f4404a29cb8b3a259290ad0f28ae47f3/CachedImage.js#L90

**Comment by chrusart** [comment]
Could you make a PR?

**Comment by kytwb** [comment]
@chrusart working on it.
