### ISSUE TITLE
NetInfo listener warning with RN 0.48

### ISSUE THREAD

**Issue by pcarion** [kfiroo/react-native-cached-image#79]
Even though your code in github did a fix for that ([PR](https://github.com/kfiroo/react-native-cached-image/commit/3d005abc2a2f40929431a6866d73592752d00a6f)), the code from npm (version 1.4.0) is still 'wrong' as it is using the wrong eventName (`change` instead of `connectionChange`

```
NetInfo.isConnected.addEventListener('change', ...)
```

The listener is also not correct:

    handleConnectivityChange(isConnected) {
        this.safeSetState({
            networkAvailable: isConnected
        });
    }

The parameter when the listener  is called is _not_ a boolean (as you expect in your code) but an [enum](http://facebook.github.io/react-native/docs/netinfo.html)

**Comment by kfiroo** [comment]
Thanks @pcarion 
I will release `v1.4.1` soon 👍
